contract_address:
  breguet: '0x77FCAa201C7A9e53876E6CEaadB7434c9652B1B8'
  tourbillon: '0xb2D2Aa035D2e487903c08c4EEd09E4D083E60763'
eth_entry_point: http://127.0.0.1:8545/
local_database: db/tourbillon.db
owner_keystore: config/owner_keystore
time_server:
- clock.stdtime.gov.tw
- watch.stdtime.gov.tw
- tick.usno.navy.mil
tourbillon_api_url: http://127.0.0.1:5000/tourbillon
