contract_address:
  breguet: '0xfcE9Dc16fD591725351C5753A6C1b8fc6935413f'
  tourbillon: '0x9C6b967956dE561f06371B58d0590aCA848D5423'
eth_entry_point: http://127.0.0.1:8545/
local_database: db/tourbillon.db
owner_keystore: config/owner_keystore
time_server:
- clock.stdtime.gov.tw
- watch.stdtime.gov.tw
- tick.usno.navy.mil
tourbillon_api_url: http://127.0.0.1:5000/tourbillon
